repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_docs
        exclude: '^lib'
      - id: terraform_fmt
        exclude: >
          (?x)^(
            [\w]+/roles/[\d\w\.]+
            )$
      - id: terraform_tfsec
        exclude: '^lib'
        files: >
          (?x)^(
            [\w]+/roles/[\d\w\.]+
            )$

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-symlinks
        exclude: >
          (?x)^(
            lib/(role|account)_template/.*
            )$
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
